# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5e95c6a50853981e2094d73e30a335f1bb98b376a6f95f4e9585e0d6b6979f05a5d2e56ed885862a1724d19221cb4d788ee25ac45f652309102f64aa273bee3

test:
  secret_key_base: 1ed2405bf57245b1813b67c6a46a4de5ed4e50959f2bbb1351a6066cb510e8e61213532f254efaa258fe15ec9e04f93f6e7395d49faabb409fc669a0169347c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
